image: registry.gitlab.com/termoshtt/accel/ubuntu18.04-cuda10.2-nightly2020-05-01:master

variables:
  AWS_DEFAULT_REGION: ap-northeast-1
  BUCKET_NAME: accel-gitlab-ci

stages:
  - docker
  - test
  - bench
  - package
  - deploy

test:cargo-clippy:
  stage: test
  script:
    - cargo clippy

test:cargo-fmt:
  stage: test
  script:
    - cargo fmt -- --check

.with_gpu:
  before_script:
    - nvidia-smi
  tags:
    - gpu
  only:
    - master
    - tags
    - /^gpu-.*/

test:accel:
  extends: .with_gpu
  stage: test
  script:
    - cargo test

test:ignored:
  extends: .with_gpu
  stage: test
  script:
    - cd accel
    - cargo test -- --ignored
  allow_failure: true

bench:
  extends: .with_gpu
  stage: bench
  script:
    - rm -rf accel/target/criterion
    - cargo bench
    - mv accel/target/criterion public/benchmark
  artifacts:
    paths:
      - public/benchmark
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[bench\]/
      - $CI_RUN_BENCHMARK

changelog:
  image: debian
  stage: test
  before_script:
    - apt update
    - apt install -y git
  script:
    - test -n "$(git diff master CHANGELOG.md)"
  except:
    - master

package:
  stage: package
  script:
    # Document of accel, accel-derive
    - cargo doc --no-deps --document-private-items
    - mv target/doc public/accel
    # Document of accel-core
    - cd accel-core
    - cargo doc
    - mv ./target/nvptx64-nvidia-cuda/doc ../public/accel-core
    - cd -
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - package
  script:
    - find public
  artifacts:
    paths:
      - public
  only:
    - master

.s3:
  image: python
  stage: deploy
  dependencies:
    - package
  before_script:
    - pip install awscli
  only:
    - master
    - tags
    - /^gpu-.*/

deploy_s3:
  extends: .s3
  script:
    - aws s3 cp public s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive --acl public-read
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: https://${BUCKET_NAME}.s3-${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}/index.html
    on_stop: clean_s3

clean_s3:
  extends: .s3
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual

.build:
  image: docker:stable
  stage: docker
  services:
    - docker:dind
  before_script:
    - apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make -C docker ${CI_JOB_NAME}
  only:
    refs:
      - master
      - tags
    changes:
      - docker/*

centos7-cuda10.0-nightly2020-01-02:
  extends: .build
centos7-cuda10.1-nightly2020-01-02:
  extends: .build
centos7-cuda10.2-nightly2020-01-02:
  extends: .build
ubuntu18.04-cuda10.0-nightly2020-01-02:
  extends: .build
ubuntu18.04-cuda10.1-nightly2020-01-02:
  extends: .build
ubuntu18.04-cuda10.2-nightly2020-01-02:
  extends: .build
centos7-cuda10.0-nightly2020-05-01:
  extends: .build
centos7-cuda10.1-nightly2020-05-01:
  extends: .build
centos7-cuda10.2-nightly2020-05-01:
  extends: .build
ubuntu18.04-cuda10.0-nightly2020-05-01:
  extends: .build
ubuntu18.04-cuda10.1-nightly2020-05-01:
  extends: .build
ubuntu18.04-cuda10.2-nightly2020-05-01:
  extends: .build
